// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type _Error = {
    error: string;
    message: string;
};

export type Program = {
    id: number;
    name: string;
    /**
     * List of valid POs for this program (e.g. PO2016, PO2023)
     */
    versions: Array<string>;
};

export type User = {
    /**
     * Version 4 UUID
     */
    id: string;
    email: string;
    name: string;
    role: 'user' | 'editor' | 'admin';
    active: 0 | 1;
    verified: 0 | 1;
    verified_at?: string | null;
    verified_until?: string | null;
    programid: number;
    created_at: string;
    updated_at: string;
};

export type UserRegister = {
    email: string;
    name: string;
    password: string;
    programid: number;
};

export type UserLogin = {
    email: string;
    password: string;
};

export type Session = {
    /**
     * opaque
     */
    id: string;
    userid: string;
    created_at: string;
    last_seen: string;
    expires_at: string;
};

export type Event = {
    id: number;
    title: string;
    cover_src?: string;
    created_at?: string;
};

export type Media = {
    id: string;
    event_id: number;
    src: string;
    /**
     * Optional thumbnail URL, currently same as src
     */
    thumb?: string;
};

export type CsrfHeader = string;

export type GetAuthCsrfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/csrf';
};

export type GetAuthCsrfResponses = {
    /**
     * CSRF token issued
     */
    200: {
        csrf: string;
    };
};

export type GetAuthCsrfResponse = GetAuthCsrfResponses[keyof GetAuthCsrfResponses];

export type PostAuthRegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Invalid payload
     */
    400: _Error;
    /**
     * Email already exists
     */
    409: _Error;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * User created
     */
    201: User;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetAuthVerifyData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/auth/verify';
};

export type GetAuthVerifyErrors = {
    /**
     * Invalid token
     */
    400: _Error;
};

export type GetAuthVerifyError = GetAuthVerifyErrors[keyof GetAuthVerifyErrors];

export type GetAuthVerifyResponses = {
    /**
     * Email verified successfully
     */
    200: {
        message?: string;
    };
};

export type GetAuthVerifyResponse = GetAuthVerifyResponses[keyof GetAuthVerifyResponses];

export type PostAuthLoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Invalid credentials
     */
    401: _Error;
    /**
     * Email not verified
     */
    403: _Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Logged in
     */
    200: User;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    headers: {
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Not authenticated
     */
    401: _Error;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Not authenticated
     */
    401: _Error;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Current user
     */
    200: User;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetUsersIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersIdErrors = {
    /**
     * Not found
     */
    404: _Error;
};

export type GetUsersIdError = GetUsersIdErrors[keyof GetUsersIdErrors];

export type GetUsersIdResponses = {
    /**
     * User
     */
    200: User;
};

export type GetUsersIdResponse = GetUsersIdResponses[keyof GetUsersIdResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Forbidden
     */
    403: _Error;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * List of users
     */
    200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/programs';
};

export type GetProgramsResponses = {
    /**
     * List of programs
     */
    200: Array<Program>;
};

export type GetProgramsResponse = GetProgramsResponses[keyof GetProgramsResponses];

export type GetProgramsIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/programs/{id}';
};

export type GetProgramsIdErrors = {
    /**
     * Not found
     */
    404: _Error;
};

export type GetProgramsIdError = GetProgramsIdErrors[keyof GetProgramsIdErrors];

export type GetProgramsIdResponses = {
    /**
     * Program
     */
    200: Program;
};

export type GetProgramsIdResponse = GetProgramsIdResponses[keyof GetProgramsIdResponses];

export type GetMediaEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/media/events';
};

export type GetMediaEventsResponses = {
    /**
     * List of events
     */
    200: Array<Event>;
};

export type GetMediaEventsResponse = GetMediaEventsResponses[keyof GetMediaEventsResponses];

export type PostMediaEventsData = {
    body: {
        title: string;
    };
    headers: {
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/media/events';
};

export type PostMediaEventsErrors = {
    /**
     * Forbidden
     */
    403: _Error;
};

export type PostMediaEventsError = PostMediaEventsErrors[keyof PostMediaEventsErrors];

export type PostMediaEventsResponses = {
    /**
     * Event created
     */
    201: Event;
};

export type PostMediaEventsResponse = PostMediaEventsResponses[keyof PostMediaEventsResponses];

export type GetMediaEventImagesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/media/events/{id}/images';
};

export type GetMediaEventImagesResponses = {
    /**
     * List of images
     */
    200: Array<Media>;
};

export type GetMediaEventImagesResponse = GetMediaEventImagesResponses[keyof GetMediaEventImagesResponses];

export type PostMediaEventImagesData = {
    body?: {
        images?: Array<Blob | File>;
        /**
         * Set the first uploaded image as event cover
         */
        cover?: boolean;
    };
    headers: {
        'X-CSRF-Token': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/media/events/{id}/images';
};

export type PostMediaEventImagesErrors = {
    /**
     * Forbidden
     */
    403: unknown;
};

export type PostMediaEventImagesResponses = {
    /**
     * Images uploaded
     */
    201: Array<Media>;
};

export type PostMediaEventImagesResponse = PostMediaEventImagesResponses[keyof PostMediaEventImagesResponses];

export type GetMediaImageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/media/images/{id}';
};

export type GetMediaImageResponses = {
    /**
     * Image content
     */
    200: Blob | File;
};

export type GetMediaImageResponse = GetMediaImageResponses[keyof GetMediaImageResponses];

export type DeleteMediaImageData = {
    body?: never;
    headers: {
        'X-CSRF-Token': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/media/images/{id}/delete';
};

export type DeleteMediaImageErrors = {
    /**
     * Forbidden
     */
    403: unknown;
};

export type DeleteMediaImageResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteMediaImageResponse = DeleteMediaImageResponses[keyof DeleteMediaImageResponses];
